/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Odex } from './Odex.js';
export * as factories from './factories/index.js';
export { Odex__factory } from './factories/Odex__factory.js';