/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Odex {
      
    export type MetadataStruct = {itemName: string, itemDescription: string, category: string}

    export type MetadataStructOutput = [itemName: string, itemDescription: string, category: string] & {itemName: string, itemDescription: string, category: string }
  
    }

  export interface OdexInterface extends Interface {
    getFunction(nameOrSignature: "buyerDeposit" | "confirmDelivery" | "createListing" | "emergencyWithdrawBuyer" | "getMetadata" | "markItemReleased" | "refundTimeout" | "sellerDeposit" | "tradeCounter" | "tradeMetadata" | "trades"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Active" | "BuyerStaked" | "ItemReleased" | "ListingCreated" | "Refunded" | "TradeCompleted"): EventFragment;

    encodeFunctionData(functionFragment: 'buyerDeposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmDelivery', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createListing', values: [BigNumberish, string, string, string]): string;
encodeFunctionData(functionFragment: 'emergencyWithdrawBuyer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMetadata', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'markItemReleased', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'refundTimeout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'sellerDeposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tradeCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'tradeMetadata', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'trades', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'buyerDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmDelivery', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdrawBuyer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markItemReleased', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundTimeout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sellerDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tradeCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tradeMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trades', data: BytesLike): Result;
  }

  
    export namespace ActiveEvent {
      export type InputTuple = [tradeId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [tradeId: bigint, timestamp: bigint];
      export interface OutputObject {tradeId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BuyerStakedEvent {
      export type InputTuple = [tradeId: BigNumberish, buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [tradeId: bigint, buyer: string, amount: bigint];
      export interface OutputObject {tradeId: bigint, buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ItemReleasedEvent {
      export type InputTuple = [tradeId: BigNumberish];
      export type OutputTuple = [tradeId: bigint];
      export interface OutputObject {tradeId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ListingCreatedEvent {
      export type InputTuple = [tradeId: BigNumberish, seller: AddressLike, price: BigNumberish, itemName: string, category: string];
      export type OutputTuple = [tradeId: bigint, seller: string, price: bigint, itemName: string, category: string];
      export interface OutputObject {tradeId: bigint, seller: string, price: bigint, itemName: string, category: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [tradeId: BigNumberish, reason: string];
      export type OutputTuple = [tradeId: bigint, reason: string];
      export interface OutputObject {tradeId: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeCompletedEvent {
      export type InputTuple = [tradeId: BigNumberish];
      export type OutputTuple = [tradeId: bigint];
      export interface OutputObject {tradeId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Odex extends BaseContract {
    
    connect(runner?: ContractRunner | null): Odex;
    waitForDeployment(): Promise<this>;

    interface: OdexInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buyerDeposit: TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    confirmDelivery: TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createListing: TypedContractMethod<
      [_price: BigNumberish, _itemName: string, _itemDescription: string, _category: string, ],
      [void],
      'nonpayable'
    >
    

    
    emergencyWithdrawBuyer: TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getMetadata: TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [Odex.MetadataStructOutput],
      'view'
    >
    

    
    markItemReleased: TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    refundTimeout: TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    sellerDeposit: TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    tradeCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tradeMetadata: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string] & {itemName: string, itemDescription: string, category: string }],
      'view'
    >
    

    
    trades: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {tradeId: bigint, seller: string, buyer: string, price: bigint, sellerStake: bigint, buyerStake: bigint, activationTime: bigint, state: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buyerDeposit'): TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'confirmDelivery'): TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createListing'): TypedContractMethod<
      [_price: BigNumberish, _itemName: string, _itemDescription: string, _category: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyWithdrawBuyer'): TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getMetadata'): TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [Odex.MetadataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'markItemReleased'): TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refundTimeout'): TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sellerDeposit'): TypedContractMethod<
      [_tradeId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'tradeCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tradeMetadata'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string] & {itemName: string, itemDescription: string, category: string }],
      'view'
    >;
getFunction(nameOrSignature: 'trades'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {tradeId: bigint, seller: string, buyer: string, price: bigint, sellerStake: bigint, buyerStake: bigint, activationTime: bigint, state: bigint }],
      'view'
    >;

    getEvent(key: 'Active'): TypedContractEvent<ActiveEvent.InputTuple, ActiveEvent.OutputTuple, ActiveEvent.OutputObject>;
getEvent(key: 'BuyerStaked'): TypedContractEvent<BuyerStakedEvent.InputTuple, BuyerStakedEvent.OutputTuple, BuyerStakedEvent.OutputObject>;
getEvent(key: 'ItemReleased'): TypedContractEvent<ItemReleasedEvent.InputTuple, ItemReleasedEvent.OutputTuple, ItemReleasedEvent.OutputObject>;
getEvent(key: 'ListingCreated'): TypedContractEvent<ListingCreatedEvent.InputTuple, ListingCreatedEvent.OutputTuple, ListingCreatedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
getEvent(key: 'TradeCompleted'): TypedContractEvent<TradeCompletedEvent.InputTuple, TradeCompletedEvent.OutputTuple, TradeCompletedEvent.OutputObject>;

    filters: {
      
      'Active(uint256,uint256)': TypedContractEvent<ActiveEvent.InputTuple, ActiveEvent.OutputTuple, ActiveEvent.OutputObject>;
      Active: TypedContractEvent<ActiveEvent.InputTuple, ActiveEvent.OutputTuple, ActiveEvent.OutputObject>;
    

      'BuyerStaked(uint256,address,uint256)': TypedContractEvent<BuyerStakedEvent.InputTuple, BuyerStakedEvent.OutputTuple, BuyerStakedEvent.OutputObject>;
      BuyerStaked: TypedContractEvent<BuyerStakedEvent.InputTuple, BuyerStakedEvent.OutputTuple, BuyerStakedEvent.OutputObject>;
    

      'ItemReleased(uint256)': TypedContractEvent<ItemReleasedEvent.InputTuple, ItemReleasedEvent.OutputTuple, ItemReleasedEvent.OutputObject>;
      ItemReleased: TypedContractEvent<ItemReleasedEvent.InputTuple, ItemReleasedEvent.OutputTuple, ItemReleasedEvent.OutputObject>;
    

      'ListingCreated(uint256,address,uint256,string,string)': TypedContractEvent<ListingCreatedEvent.InputTuple, ListingCreatedEvent.OutputTuple, ListingCreatedEvent.OutputObject>;
      ListingCreated: TypedContractEvent<ListingCreatedEvent.InputTuple, ListingCreatedEvent.OutputTuple, ListingCreatedEvent.OutputObject>;
    

      'Refunded(uint256,string)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    

      'TradeCompleted(uint256)': TypedContractEvent<TradeCompletedEvent.InputTuple, TradeCompletedEvent.OutputTuple, TradeCompletedEvent.OutputObject>;
      TradeCompleted: TypedContractEvent<TradeCompletedEvent.InputTuple, TradeCompletedEvent.OutputTuple, TradeCompletedEvent.OutputObject>;
    
    };
  }